name: Pull Request Template Chooser

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - development
      - qa

jobs:
  choose-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Select Template
        id: template
        run: |
          FEATURE_BRANCH_PATTERN="module-sdk"
          BUGFIX_BRANCH_PATTERN="development"
          echo "${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" == $FEATURE_BRANCH_PATTERN* ]]; then
            echo "::set-output name=template_path::.github/PULL_REQUEST_TEMPLATE/template1.md"
          elif [[ "${{ github.head_ref }}" == $BUGFIX_BRANCH_PATTERN* ]]; then
            echo "::set-output name=template_path::.github/PULL_REQUEST_TEMPLATE/template2.md"
          else
            echo "::set-output name=template_path::.github/PULL_REQUEST_TEMPLATE/pull_request_template.md"
          fi

      - name: Read Template Content
        id: read-template
        run: echo "::set-output name=template::$(cat ${{ steps.template.outputs.template_path }})"

      - name: Update Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.read-template.outputs.template }}
